Fix a lot of typos
BZFlag-Dev/bzflag pull request #362
Opened 2024-09-23 16:05 UTC by TheGiraffe3

Detected using automated processes.

2024-10-17 04:46 UTC, TheGiraffe3 commented
@blast007 could I get a review please?

2024-10-22 15:22 UTC, RighthandSon requested changes
There aren't many devs and things tend to take awhile here, especially on a big PR with lots of changes like this one.
Most changes look pretty good, the two that I have questions about are:
UnSilence vs Unsilence Is this really a needed change, given the use case it seems fine to me as is.
The removal of misc/libtool.m4 while I haven't dug into where/why this is used, why is it lumped in with a bunch of spelling fixes?

2024-10-22 15:22 UTC, RighthandSon commented on AUTHORS
> +Bj�rn Augustsson
```suggestion
Björn Augustsson
```
I don't know what this was changed to, it doesn't show properly on my linux machine, better to leave all the names as they were I think.

2024-10-22 15:22 UTC, RighthandSon commented on AUTHORS
> +Daniel L�onard <fork@videotron.ca>
```suggestion
Daniel Léonard <fork@videotron.ca>
```

2024-10-22 15:22 UTC, RighthandSon commented on AUTHORS
> +Fran�ois Revol (mmu_man)
```suggestion
François Revol (mmu_man)
```

2024-10-22 15:22 UTC, RighthandSon commented on AUTHORS
> +J�rgen Pedersen Tjern� (daxxar)
```suggestion
Jørgen Pedersen Tjernø (daxxar)
```

2024-10-22 15:22 UTC, RighthandSon commented on AUTHORS
> +Am�rico Monteiro
```suggestion
Américo Monteiro
```

2024-10-22 15:22 UTC, RighthandSon commented on AUTHORS
> +J�rgen Pedersen Tjern� (daxxar)
```suggestion
Jørgen Pedersen Tjernø (daxxar)
```

2024-10-22 15:22 UTC, RighthandSon commented on data/l10n/bzflag_da.po
There are some typos I see... but it seems like a deliberate choice to have it as UnSilence. Perhaps I'm used to it, but I think it's fine as it is.
This goes for all of such files/changes..

2024-10-22 15:22 UTC, RighthandSon commented on src/bzflag/BackgroundRenderer.cxx
> +        // draw ground receiver, computting lighting at each vertex ourselves
```suggestion
        // draw ground receiver, computing lighting at each vertex ourselves
```

2024-10-22 15:22 UTC, RighthandSon commented on src/bzflag/BackgroundRenderer.cxx
> +        // draw ground receiver, computting lighting at each vertex ourselves
```suggestion
        // draw ground receiver, computing lighting at each vertex ourselves
```

2024-10-22 15:22 UTC, RighthandSon commented on src/bzflag/ShotStrategy.h
> + *  strategy encapsulates the algorithm for computting
```suggestion
 *  strategy encapsulates the algorithm for computing
```

2024-10-22 15:22 UTC, RighthandSon commented on src/bzfs/bzfsAPI.cxx
> +BZF_API bool bz_computtingPlayerScore( void )
```suggestion
BZF_API bool bz_computingPlayerScore( void )
```

2024-10-22 15:22 UTC, RighthandSon commented on src/bzfs/bzfsAPI.cxx
> +BZF_API bool bz_computtingTeamScore( void )
```suggestion
BZF_API bool bz_computingTeamScore( void )
```

2024-10-22 15:22 UTC, RighthandSon commented on src/game/Intersect.cxx
> +/** Computting ray travel time to the plane described by 3 points
```suggestion
/** Computing ray travel time to the plane described by 3 points
```

2024-10-22 15:22 UTC, RighthandSon commented on src/game/Intersect.cxx
> +    // computting unnormalized distance projecting the distance on versor
```suggestion
    // computing unnormalized distance projecting the distance on versor
```

2024-10-22 15:22 UTC, RighthandSon commented on man/bzflag.6.in
> +Uses \fIlongitude\fR when computting celestial object positions.
```suggestion
Uses \fIlongitude\fR when computing celestial object positions.
```

2024-10-22 15:22 UTC, RighthandSon commented on include/bzfsAPI.h
> +BZF_API bool bz_computtingPlayerScore( void );
What are we putting around? lets keep it to computing shall we?
```suggestion
BZF_API bool bz_computingPlayerScore( void );
```

2024-10-22 15:22 UTC, RighthandSon commented on include/bzfsAPI.h
> +BZF_API bool bz_computtingTeamScore( void );
```suggestion
BZF_API bool bz_computingTeamScore( void );
```

2024-10-22 15:22 UTC, RighthandSon commented on man/bzflag.6.in
> +Uses \fIlatitude\fR when computting celestial object positions.
```suggestion
Uses \fIlatitude\fR when computing celestial object positions.
```

2024-10-22 16:02 UTC, TheGiraffe3 commented
> The removal of misc/libtool.m4 while I haven't dug into where/why this is used, why is it lumped in with a bunch of spelling fixes?

See the original PR.

Sorry about the computting thing... I guess I need to not assume that replacing "puting" with "putting" won't change anything else.

2024-10-22 16:10 UTC, RighthandSon commented
Ahh, my bad for not looking at the original. :+1:

2024-10-22 18:33 UTC, agatha2 commented
There are many good typo fixes, but there are a few strange ones I think are wrong (e.g. "computing" has been changed to "computting").

The "AUTHORS" file appears to have changed from one prehistoric extended-ASCII regional encoding into . . . _something else;_ I have no idea . . . instead of to UTF-8. This is easy to see in [the online diff](https://github.com/BZFlag-Dev/bzflag/pull/362/commits/60deadb9cc0920d1039c4de2a29d9a53adb30706#diff-ab6af77435f58cc0c9d4c31dfe05656e45187cc7c7fc02aada401a7642125463). For example, "Léonard" was written (4c e9 6f 6e 61 72 64), but was changed to (4c ef bf bd 6f 6e 61 72 64). That is, "é" ([U+00E9](https://symbl.cc/en/00E9/)) changed from (e9) to (ef bf bd). When in actuality "é" should be (c3 a9) in UTF-8.

2024-11-30 22:08 UTC, merged